agent:
  label: jenkins-go
  container: go
  dir: /home/jenkins/go/src/github.com/thefirstofthe300/kore
pipelines:
  release:
    setup:
      steps:
      - groovy: git clone 'https://github.com/thefirstofthe300/kore.git'
        name: checkout-scm